#
# Copyright (c) 2019 Jonathan McGee <broken.source@etherealwake.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
package(default_visibility = ["//visibility:public"])

# Cortex-M0/M0+/M1
constraint_value(
    name = "armv6-m",
    constraint_setting = "//constraints/arch",
)

# Cortex-A5/A7/A8/A9/A12/A15/A17
constraint_value(
    name = "armv7-a",
    constraint_setting = "//constraints/arch",
)

# Cortex-M3
constraint_value(
    name = "armv7-m",
    constraint_setting = "//constraints/arch",
)

# Cortex-M4/M7
constraint_value(
    name = "armv7e-m",
    constraint_setting = "//constraints/arch",
)

# Cortex-R4/R5/R7/R8
constraint_value(
    name = "armv7-r",
    constraint_setting = "//constraints/arch",
)

# Cortex-A32/A35/A53/A55/A57/A72/A73/A75/A76
constraint_value(
    name = "armv8-a",
    constraint_setting = "//constraints/arch",
)

# Cortex-M23
constraint_value(
    name = "armv8-m.base",
    constraint_setting = "//constraints/arch",
)

# Cortex-M33/M35P
constraint_value(
    name = "armv8-m.main",
    constraint_setting = "//constraints/arch",
)

# Cortex-R52
constraint_value(
    name = "armv8-r",
    constraint_setting = "//constraints/arch",
)
