#
# Copyright (c) 2019 Jonathan McGee <broken.source@etherealwake.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
package(default_visibility = ["//visibility:public"])

#
# ARMv7-A
#

config_setting(
    name = "cortex-a5",
    constraint_values = [
        "//constraints/core/arm:cortex-a5",
    ],
)

config_setting(
    name = "cortex-a7",
    constraint_values = [
        "//constraints/core/arm:cortex-a7",
    ],
)

config_setting(
    name = "cortex-a8",
    constraint_values = [
        "//constraints/core/arm:cortex-a8",
    ],
)

config_setting(
    name = "cortex-a9",
    constraint_values = [
        "//constraints/core/arm:cortex-a9",
    ],
)

config_setting(
    name = "cortex-a12",
    constraint_values = [
        "//constraints/core/arm:cortex-a12",
    ],
)

config_setting(
    name = "cortex-a15",
    constraint_values = [
        "//constraints/core/arm:cortex-a15",
    ],
)

config_setting(
    name = "cortex-a17",
    constraint_values = [
        "//constraints/core/arm:cortex-a17",
    ],
)

#
# ARMv8-A
#

config_setting(
    name = "cortex-a32",
    constraint_values = [
        "//constraints/core/arm:cortex-a32",
    ],
)

config_setting(
    name = "cortex-a35",
    constraint_values = [
        "//constraints/core/arm:cortex-a35",
    ],
)

config_setting(
    name = "cortex-a53",
    constraint_values = [
        "//constraints/core/arm:cortex-a53",
    ],
)

config_setting(
    name = "cortex-a55",
    constraint_values = [
        "//constraints/core/arm:cortex-a55",
    ],
)

config_setting(
    name = "cortex-a57",
    constraint_values = [
        "//constraints/core/arm:cortex-a57",
    ],
)

config_setting(
    name = "cortex-a72",
    constraint_values = [
        "//constraints/core/arm:cortex-a72",
    ],
)

config_setting(
    name = "cortex-a73",
    constraint_values = [
        "//constraints/core/arm:cortex-a73",
    ],
)

config_setting(
    name = "cortex-a75",
    constraint_values = [
        "//constraints/core/arm:cortex-a75",
    ],
)

config_setting(
    name = "cortex-a76",
    constraint_values = [
        "//constraints/core/arm:cortex-a76",
    ],
)

#
# ARMv6-M
#

config_setting(
    name = "cortex-m0",
    constraint_values = [
        "//constraints/core/arm:cortex-m0",
    ],
)

config_setting(
    name = "cortex-m0plus",
    constraint_values = [
        "//constraints/core/arm:cortex-m0plus",
    ],
)

config_setting(
    name = "cortex-m1",
    constraint_values = [
        "//constraints/core/arm:cortex-m1",
    ],
)

#
# ARMv7-M
#

config_setting(
    name = "cortex-m3",
    constraint_values = [
        "//constraints/core/arm:cortex-m3",
    ],
)

#
# ARMv7E-M
#

config_setting(
    name = "cortex-m4",
    constraint_values = [
        "//constraints/core/arm:cortex-m4",
    ],
)

config_setting(
    name = "cortex-m7",
    constraint_values = [
        "//constraints/core/arm:cortex-m7",
    ],
)

#
# ARMv8-M
#

config_setting(
    name = "cortex-m23",
    constraint_values = [
        "//constraints/core/arm:cortex-m23",
    ],
)

config_setting(
    name = "cortex-m33",
    constraint_values = [
        "//constraints/core/arm:cortex-m33",
    ],
)

config_setting(
    name = "cortex-m35",
    constraint_values = [
        "//constraints/core/arm:cortex-m35",
    ],
)

#
# ARMv7-R
#

config_setting(
    name = "cortex-r4",
    constraint_values = [
        "//constraints/core/arm:cortex-r4",
    ],
)

config_setting(
    name = "cortex-r5",
    constraint_values = [
        "//constraints/core/arm:cortex-r5",
    ],
)

config_setting(
    name = "cortex-r7",
    constraint_values = [
        "//constraints/core/arm:cortex-r7",
    ],
)

config_setting(
    name = "cortex-r8",
    constraint_values = [
        "//constraints/core/arm:cortex-r8",
    ],
)

#
# ARMv8-R
#

config_setting(
    name = "cortex-r52",
    constraint_values = [
        "//constraints/core/arm:cortex-r52",
    ],
)
