#
# Copyright (c) 2019 Jonathan McGee <broken.source@etherealwake.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
package(default_visibility = ["//visibility:public"])

config_setting(
    name = "android",
    constraint_values = [
        "//constraints/os:android",
    ],
)

config_setting(
    name = "dragonfly",
    constraint_values = [
        "//constraints/os:dragonfly",
    ],
)

config_setting(
    name = "freebsd",
    constraint_values = [
        "//constraints/os:freebsd",
    ],
)

config_setting(
    name = "ios",
    constraint_values = [
        "//constraints/os:ios",
    ],
)

config_setting(
    name = "linux",
    constraint_values = [
        "//constraints/os:linux",
    ],
)

config_setting(
    name = "macosx",
    constraint_values = [
        "//constraints/os:macosx",
    ],
)

config_setting(
    name = "netbsd",
    constraint_values = [
        "//constraints/os:netbsd",
    ],
)

config_setting(
    name = "none",
    constraint_values = [
        "//constraints/os:none",
    ],
)

config_setting(
    name = "openbsd",
    constraint_values = [
        "//constraints/os:openbsd",
    ],
)

config_setting(
    name = "windows",
    constraint_values = [
        "//constraints/os:windows",
    ],
)
